config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'megasoft/home#index'
  namespace :megasoft do
    namespace :api do
      namespace :v1, defaults: { format: 'json' } do
         post 'calculator/calculate', to: 'calculator#calculate'
      end
    end

    namespace :admin do
      get '/', to: 'operator_usages#index'
      get '/get_report', to: 'operator_usages#get_report'
    end

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/operation/add.rb
class Operation::Add < Operator

  def validate_input(input)
    if input.include?(false)
      raise 'Invalid input'
    end
  end

  def evaluate(input)
    input.inject(:+)
  end

end

app/models/operation/cube_root.rb
class Operation::CubeRoot < Operator

  def validate_input(input)    
    if input.include?(false) || input.length > 1 || (input.length == 0)
      raise 'Invalid input'
    end
  end

  def evaluate(input)
    Math.cbrt(input[0])
  end

end

app/models/operation/divide.rb
class Operation::Divide < Operator

  def validate_input(input)
    if input.include?(false) || (input.length != 2) || (input[1] == 0)
      raise 'Invalid input'
    end
  end

  def evaluate(input)
    input[0].to_f/input[1]
  end

end

app/models/operation/factorial.rb
class Operation::Factorial < Operator

  def validate_input(input)    
    if input.include?(false) || input.length > 1 || input[0] < 0
      raise 'Invalid input'
    end
  end

  def evaluate(input)
    input[0] == 0 ? 1 : Math.gamma(input[0]+1)
  end

end

app/models/operation/multiply.rb
class Operation::Multiply < Operator

  def validate_input(input)
    if input.include?(false)
      raise 'Invalid input'
    end
  end

  def evaluate(input)
    input.inject(:*)
  end

end

app/models/operation/power.rb
class Operation::Power < Operator

  def validate_input(input)
    if input.include?(false) || (input.length != 2)
      raise 'Invalid input'
    end
  end

  def evaluate(input)
    (input[0] ** input[1]).to_f
  end

end

app/models/operation/square_root.rb
class Operation::SquareRoot < Operator

  def validate_input(input)    
    if input.include?(false) || input.length > 1 || input[0] < 0
      raise 'Invalid input'
    end
  end

  def evaluate(input)
    Math.sqrt(input[0])
  end

end

app/models/operation/subtract.rb
class Operation::Subtract < Operator

  def validate_input(input)    
    if input.include?(false) || input.length > 2
      raise 'Invalid input'
    end
  end

  def evaluate(input)
    input[0] - input[1]
  end

end

app/models/operator.rb
class Operator < ApplicationRecord

  has_many :operator_usages

	validates :type, :display_sign, :action, presence: true, uniqueness: true
  validates :position, numericality: true, uniqueness: true

  def calculate(input)
    input = parse_input(input)
    validate_input(input)
    result = evaluate(input)
    track_usage(input)
    result
  end

  def parse_input(input)
    input.map{ |val|  (to_integer(val) || to_float(val))}
  end

  def validate_input
    raise NotImplementedError, "validate should be implemented in a sub-class of Operator"
  end

  def track_usage(input)
    count = input.length == 1 ? 1 : (input.length - 1)
    operational_usage = self.operator_usages.find_or_create_by(day: Date.today)
    operational_usage.with_lock do
      operational_usage.usage += count
      operational_usage.save!
    end
  end

  def to_integer(val)
    Integer(val) rescue false
  end

  def to_float(val)
    Float(val) rescue false
  end

end

app/models/operator_usage.rb
require 'csv'
class OperatorUsage < ApplicationRecord

	belongs_to :operator

  def self.monthly_report(mon = Date.today.month)
    self.where('extract(month from day) = ?', mon)
  end

  def self.weekly_report
    self.where('day >= ? and day <= ?', Date.today.beginning_of_week, Date.today.end_of_week)
  end

  def self.daily_report
    self.where('day = ?', Date.today)
  end

  def self.to_csv(operator_usages)
    Enumerator.new do |response_csv|
      response_csv << CSV.generate_line(%w[operator count date])
      operator_usages.each do |ou|
        response_csv << CSV.generate_line([ou.operator.display_sign, ou.usage, ou.day]) 
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/megasoft/admin/base_controller.rb
module Megasoft
  module Admin
    class BaseController < ApplicationController

      http_basic_authenticate_with name: ENV['ADMIN_AUTHENTICATION_USERNAME'], password: ENV['ADMIN_AUTHENTICATION_PASSWORD']

    end
  end
end

app/controllers/megasoft/admin/operator_usages_controller.rb
module Megasoft
  module Admin
	  class OperatorUsagesController < BaseController

      def index
        @operator_usages = OperatorUsage.includes(:operator)
        if params[:start_date].present?
          @start_date = params[:start_date]
          @operator_usages = @operator_usages.where('day >= ?', params[:start_date].to_date)
        end
        if params[:end_date].present?
          @end_date = params[:end_date]
          @operator_usages = @operator_usages.where('day <= ?', params[:end_date].to_date)
        end
        @operator_usages = @operator_usages
                            .order('operator_usages.day desc','operators.position asc')
                            .paginate(page: params[:page], per_page: 10)
      end

      def get_report
        @operator_usages = OperatorUsage.includes(:operator)
        case params[:type]
        when "monthly"
          @operator_usages = @operator_usages.monthly_report
        when "weekly"
          @operator_usages = @operator_usages.weekly_report
        when "daily"
          @operator_usages = @operator_usages.daily_report
        else
        end 
        send_csv(@operator_usages, params[:type])
      end

      private
      # csv
      def send_csv(operator_usages, type)
        csv = OperatorUsage.to_csv(operator_usages)

        file_name = "operator_usages-#{type}-#{Date.today}.csv"

        headers['Content-Type'] = 'text/csv'
        headers['Content-disposition'] = "attachment; filename='#{file_name}'"

        # set streaming headers
        headers['X-Accel-Buffering'] = 'no'
        headers['Cache-Control'] ||= 'no-cache'

        headers.delete('Content-Length')

        # response
        response.status = 200
        self.response_body = csv
      end
	  	
	  end
	end
end

app/controllers/megasoft/api/v1/base_controller.rb
module Megasoft
  module Api
    module V1
      class BaseController < ApplicationController
        include ActionController::HttpAuthentication::Token::ControllerMethods
        skip_before_action :verify_authenticity_token

        before_action :authenticate

        protected

        # Authenticate the user with token based authentication
        def authenticate
          authenticate_token || render_unauthorized
        end

        def authenticate_token
          authenticate_with_http_token do |token, options|
            token == ENV['API_AUTHENTICATION_TOKEN']
          end
        end

        def render_unauthorized
          render json: {message: "You are unauthorized to perform this action"}, status: 401
        end

      end
    end
  end
end

app/controllers/megasoft/api/v1/calculator_controller.rb
module Megasoft
  module Api
    module V1
      class CalculatorController < BaseController

        def calculate
          operator = Operator.find_by_action calculator_params[:operation]
          if operator && calculator_params[:input].present?
            begin
              result = operator.calculate(calculator_params[:input])
              render json: { result: result }, status: 201
            rescue Exception => e
              render json: { message: e.message } , status: :bad_request
            end
          else
            render json: { message: "Invalid request" } , status: :bad_request
          end
        end

        private

        def calculator_params
          params.permit(:operation, input: [])
        end
      
      end
    end
  end
end

app/controllers/megasoft/home_controller.rb
module Megasoft
  class HomeController < ApplicationController

    def index
      @operators = {}
      Operator.all.map{|d| @operators[d.position] = {display_sign: d.display_sign, action: d.action} }
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MegasoftCalc</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="jumbotron">
      <h1>Megasoft Calculator</h1>      
    </div>
    <%= yield %>
  </body>
</html>

app/views/megasoft/admin/operator_usages/index.html.erb
<div class="container text-center" id="calc">
  <div class='col-md-12 ' style="display: grid;">
    <div class="date_filters">
     <%= form_tag(megasoft_admin_path, method: "get", class: "date_filters") do %>
        <div class="filter"><%= text_field_tag :start_date, @start_date, class: 'datepicker', placeholder: 'Start date' %></div>
        <div class="filter"><%= text_field_tag :end_date, @end_date, class: 'datepicker', placeholder: 'End date' %></div>
        <div class="filter"><%= submit_tag "Submit", class: 'btn btn-default' %></div>
    <% end %>
    </div>
    <div class="reports">
      <div class="report_btn"><%= button_to "Monthly report", megasoft_admin_get_report_path(format: 'csv'), method: :get, params: { type: "monthly" }, class: "btn btn-default" %></div>
      <div class="report_btn"><%= button_to "Weekly report", megasoft_admin_get_report_path(format: 'csv'), method: :get, params: { type: "weekly" }, class: "btn btn-default" %></div>
      <div class="report_btn"><%= button_to "Daily report", megasoft_admin_get_report_path(format: 'csv'), method: :get, params: { type: "daily" }, class: "btn btn-default" %></div>
    </div>
  </div>
  <div class="calcBG col-md-3 col-md-offset-3 text-center">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Operator</th>
          <th scope="col">Count</th>
          <th scope="col">Date</th>
        </tr>
      </thead>
      <tbody>
        <% @operator_usages.each_with_index do |ou, index| %>
          <tr>
            <th scope="row"><%= index %></th>
            <td><%= ou.operator.display_sign %></td>
            <td><%= ou.usage %></td>
            <td><%= ou.day %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @operator_usages %>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function() {
    $('.datepicker').datepicker({format: 'dd/mm/yyyy'});
  });
</script>

app/views/megasoft/home/index.html.erb
<div class="container text-center" id="calc">
  <div class="calcBG col-md-3 col-md-offset-3 text-center">
    <div class="row" id="result">
      <input type="text" class="screen text-right" name="result" readonly>
    </div>
    <div class="row">
      <button id="allClear" type="button" data-val="allClear" class="btn btn-danger">AC</button>
      <button id="clear" type="button" data-val="clear" class="btn btn-warning" style="width: 32%;">CE</button>
      <button id="<%= @operators[7][:action] %>" type="button" data-val="<%= @operators[7][:action] %>" class="btn btn-info ops"><%= @operators[7][:display_sign] %></button>
      <button id="<%= @operators[8][:action] %>" type="button" data-val="<%= @operators[8][:action] %>" class="btn btn-info ops"><%= @operators[8][:display_sign] %></button>
    </div>
    <div class="row">
      <button id="7" type="button" data-val="7" class="btn btn-info num">7</button>
      <button id="8" type="button" data-val="8" class="btn btn-info num">8</button>
      <button id="9" type="button" data-val="9" class="btn btn-info num">9</button>
      <button id="<%= @operators[5][:action] %>" type="button" data-val="<%= @operators[5][:action] %>" class="btn btn-info ops"><%= @operators[5][:display_sign] %></button>
      <button id="<%= @operators[6][:action] %>" type="button" data-val="<%= @operators[6][:action] %>" class="btn btn-info ops"><%= @operators[6][:display_sign] %></button>
    </div>
    <div class="row">
      <button id="4" type="button" data-val="4" class="btn btn-info num">4</button>
      <button id="5" type="button" data-val="5" class="btn btn-info num">5</button>
      <button id="6" type="button" data-val="6" class="btn btn-info num">6</button>
      <button id="<%= @operators[3][:action] %>" type="button" data-val="<%= @operators[3][:action] %>" class="btn btn-info ops"><%= @operators[3][:display_sign] %></button>
      <button id="<%= @operators[4][:action] %>" type="button" data-val="<%= @operators[4][:action] %>" class="btn btn-info ops"><%= @operators[4][:display_sign] %></button>
    </div>
    <div class="row">
      <button id="1" type="button" data-val="1" class="btn btn-info num">1</button>
      <button id="2" type="button" data-val="2" class="btn btn-info num">2</button>
      <button id="3" type="button" data-val="3" class="btn btn-info num">3</button>
      <button id="<%= @operators[2][:action] %>" type="button" data-val="<%= @operators[2][:action] %>" class="btn btn-info ops" style="width: 32%;"><%= @operators[2][:display_sign] %></button>
    </div>
    <div class="row">
      <button id="0" type="button" data-val="0" class="btn btn-info num">0</button>
      <button id="." type="button" data-val="." class="btn btn-info num">.</button>
      <button id="equals" type="button" data-val="=" class="btn btn-success">=</button>
      <button id="/" type="button" data-val="<%= @operators[1][:display_sign] %>" class="btn btn-info ops" style="width: 32%;"><%= @operators[1][:display_sign] %></button>
    </div>
  </div>
</div>